#!/bin/bash

# Quick Wins - Immediate Project Improvements
# Safe to run before tomorrow's meeting (5-10 minutes)

set -e

echo "🎯 Applying quick project improvements..."

# 1. Create docs folder and move documentation
echo "📚 Step 1/4: Organizing documentation..."
mkdir -p docs/{deployment,development,setup,architecture}

# Helper function to move files (handles both tracked and untracked)
move_file() {
    if [ -f "$1" ]; then
        if git ls-files --error-unmatch "$1" >/dev/null 2>&1; then
            git mv "$1" "$2"
        else
            mv "$1" "$2"
        fi
    fi
}

move_file "deploy.md" "docs/deployment/"
move_file "aws_migration.md" "docs/deployment/"
move_file "classification_matrix.md" "docs/development/"
move_file "meeting_questions.md" "docs/development/"
move_file "evidence_documentation.md" "docs/development/"
move_file "TIMING_DIFFERENCE_SETUP.md" "docs/setup/"
move_file "PG-01 Diagram.png" "docs/architecture/"

# 2. Create data folder for outputs and credentials
echo "📊 Step 2/4: Creating data directory..."
mkdir -p data/{credentials,outputs}

# 3. Update .gitignore
echo "🚫 Step 3/4: Updating .gitignore..."
cat >> .gitignore << EOF

# Data and credentials (added by quick_wins.sh)
data/
credentials.json
*.csv
!tests/fixtures/*.csv
EOF

# 4. Create a simple README in data folder
echo "📝 Step 4/4: Creating data folder README..."
cat > data/README.md << EOF
# Data Directory

This directory is for local data storage and is excluded from git.

## Structure

- \`credentials/\` - Google Cloud service account credentials
  - Place your \`credentials.json\` file here
- \`outputs/\` - Analysis outputs (CSV files, reports)
  - Generated by bridge analysis scripts
  - Timing difference results
  - Evidence packages

## Security Note

⚠️ **NEVER commit credentials to git!**

This entire directory is gitignored. Keep sensitive data here.
EOF

echo "✅ Quick improvements complete!"
echo ""
echo "📋 What Changed:"
echo "  ✓ Documentation organized in docs/ folder"
echo "  ✓ Created data/ folder for credentials and outputs"
echo "  ✓ Updated .gitignore to exclude sensitive data"
echo ""
echo "📝 Next Steps:"
echo "  1. Move your credentials.json to data/credentials/"
echo "  2. Update CREDENTIALS_FILE path in timing_difference_analysis.py:"
echo "     CREDENTIALS_FILE = 'data/credentials/credentials.json'"
echo "  3. Commit changes: git commit -m 'docs: organize project structure'"
echo ""
echo "🚀 Ready for tomorrow's meeting!"
