SELECT
    [ID_COMPANY],
    [COMPANY_NAME],
    [COUNTRY_CODE],
    [COUNTRY_NAME],
    [CLOSING_DATE],
    [REFRESH_DATE],
    [GROUP_COA_ACCOUNT_NO],
    [GROUP_COA_ACCOUNT_NAME],
    [REAL_COA],
    [CURRENCY],
    [FX_RATE],
    [BALANCE_AT_DATE],
    [BUSLINE_CODE],
    [REPORTING_COUNTRY_CODE],
    [REPORTING_COUNTRY_NAME],
    [PARTNER_CODE],
    [IC_PARTNER_CODE],
    [IS_RECHARGE],
    [IS_RETAINED_EARNINGS],
    [CONSO_ACCOUNT_NO],
    [CONSO_ACCOUNT_NAME],
    [IFRS_LEVEL_1_NAME],
    [IFRS_LEVEL_2_NAME],
    [IFRS_LEVEL_3_NAME],
    [IS_INTERCO]
FROM [AIG_Nav_Jumia_Reconciliation].[dbo].[V_BS_ANAPLAN_IMPORT_IFRS_MAPPING_CURRENCY_SPLIT]
WHERE [CLOSING_DATE] = '{cutoff_date}'
AND [GROUP_COA_ACCOUNT_NO] IN {gl_accounts}
